### ISSUE TITLE
Some options in the documentation of commands are not getting rendered properly

### ISSUE THREAD

**Issue by justinjereza** [containers/podman.io#66]
Example:

![image](https://user-images.githubusercontent.com/5376865/236712479-9b8d957a-03a7-4120-8e16-d1844888bdfa.png)

**Comment by lilyx13** [comment]
This one might be a bit tricky. the @@option syntax seems to be used to pull content in from the options however that doesn't work anymore with these files since they were imported into docusaurus. @mairin do you think that we should temporarily point the docs commands to the manpages website docs.podman.io?

**Comment by lilyx13** [comment]
ah that makes sense. Yeah I did just copy them over. I'll bring this up in the maintainer meeting today and take action from there.
